from src.models.vrp_solution import VRPSolution

def two_opt_single_truck(solution: VRPSolution) -> VRPSolution:
    """
    Applies the 2-opt algorithm to an initial VRP solution while respecting constraints:
      - All loadings must come before unloadings in each route
      - At most one charger per route
      - Each route must start and end at a parking

    Parameters:
        solution (VRPSolution): Initial VRP solution (e.g., generated by nearest neighbour)

    Returns:
        VRPSolution: New solution with optimized routes
    """
    instance = solution.instance
    optimized_solution = VRPSolution(instance)

    for route in solution.routes:
        best_route = route.copy()
        improved = True

        while improved:
            improved = False
            n = len(best_route)

            # Consider only internal nodes (skip first and last parking)
            for i in range(1, n - 2):
                for j in range(i + 1, n - 1):
                    segment = best_route[i:j+1]
                    segment_types = [instance.locations[loc]['node'] for loc in segment]

                    # Skip if segment mixes loading and unloading
                    if 'loading' in segment_types and 'unloading' in segment_types:
                        continue

                    # Skip if segment contains more than one charger
                    if segment_types.count('charger') > 1:
                        continue

                    # Perform 2-opt inversion
                    new_route = best_route[:i] + segment[::-1] + best_route[j+1:]

                    # Precompute old and new route distances
                    old_distance = sum(
                        instance.get_distance(best_route[k], best_route[k+1]) for k in range(n-1)
                    )
                    new_distance = sum(
                        instance.get_distance(new_route[k], new_route[k+1]) for k in range(n-1)
                    )

                    # Accept new route if it improves distance
                    if new_distance < old_distance:
                        best_route = new_route
                        improved = True
                        break  # restart search after improvement
                if improved:
                    break

        # Add optimized route to the new solution
        optimized_solution.add_route(best_route)

    # Check full solution feasibility
    optimized_solution.complete_feasibility()
    return optimized_solution
